### ISSUE TITLE
karma fails for Tour of Heroes tutorial, part 5, Routing

### ISSUE THREAD

**Issue by psnider** [angular/quickstart#200]
I've struggled with another problem getting karma to work for the Tour-of-Heroes tutorial.
In the final step of part 5, Routing - [Styling the App](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html#styling-the-app), code is introduced that causes the karma tests to fail with this misleading error:
```
    Chrome 52.0.2743 (Mac OS X 10.11.6) AppComponent with TCB should instantiate component FAILED
[1] 	Error: This test module uses the component AppComponent which is using a "templateUrl", but they were never compiled. Please call "TestBed.compileComponents" before your test.
[1] 	    at TestBed._initIfNeeded (/Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/@angular/core/testing/test_bed.js:219:27)
[1] 	    at TestBed.createComponent (/Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/@angular/core/testing/test_bed.js:296:14)
[1] 	    at Function.TestBed.createComponent (/Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/@angular/core/testing/test_bed.js:126:29)
[1] 	    at Object.eval (/Users/peter/devel/tutorials/angular2-quickstart-rc5/generated/browser-angular2/app/app.component.spec.js:22:41)
[1] 	    at ZoneDelegate.invoke (/Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/zone.js/dist/zone.js:332:29)
[1] 	    at Zone.run (/Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/zone.js/dist/zone.js:225:44)
[1] 	    at /Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/zone.js/dist/zone.js:591:58
[1] 	    at ZoneDelegate.invokeTask (/Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/zone.js/dist/zone.js:365:38)
[1] 	    at Zone.runTask (/Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/zone.js/dist/zone.js:265:48)
[1] 	    at drainMicroTaskQueue (/Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/zone.js/dist/zone.js:497:36)
[1] 	    at XMLHttpRequest.ZoneTask.invoke (/Users/peter/devel/tutorials/angular2-quickstart-rc5/node_modules/zone.js/dist/zone.js:437:26)
```

But components/browser-angular2/app/app.component.ts doesn't use the **templateUrl** field!

**Comment by psnider** [comment]
I believe I have a solution:

After working through the tutorial slowly, I discovered that the problem is introduced when the **routerLinkActive** directive is added.

I added this import to app/app.component.ts, and it seems to resolve the karma problems.
```
import { RouterLinkActive } from '@angular/router';
```

Please let me know if this is a correct fix.
If it is, please update the tutorial.

Also, it seems that the error message should be made more specific, if possible. 
It gave me no information that helped me locate the source of  the problem.

**Comment by filipesilva** [comment]
That is not the correct approach, no. We're putting the finishing touches on the testing chapter in www.angular.io which will address such situations.
