### ISSUE TITLE
Hello I am facing this issue. 

### ISSUE THREAD

**Issue by aminsmartsense** [angular/quickstart#300]
[0] fs.js:1431
[0]     throw error;
[0]     ^
[0] 
[0] Error: watch /var/www/html/angular/quickstart ENOSPC
[0]     at exports._errnoException (util.js:1026:11)
[0]     at FSWatcher.start (fs.js:1429:19)
[0]     at Object.fs.watch (fs.js:1456:11)
[0]     at Object.watchDirectory (/var/www/html/angular/quickstart/node_modules/typescript/lib/tsc.js:1727:32)
[0]     at Object.executeCommandLine (/var/www/html/angular/quickstart/node_modules/typescript/lib/tsc.js:39774:43)
[0]     at Object.<anonymous> (/var/www/html/angular/quickstart/node_modules/typescript/lib/tsc.js:40095:4)
[0]     at Module._compile (module.js:570:32)
[0]     at Object.Module._extensions..js (module.js:579:10)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0] tsc -w exited with code 1
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync config **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   watchOptions: { ignored: 'node_modules' },
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: watch . ENOSPC
[1]     at exports._errnoException (util.js:1026:11)
[1]     at FSWatcher.start (fs.js:1429:19)
[1]     at Object.fs.watch (fs.js:1456:11)
[1]     at createFsWatchInstance (/var/www/html/angular/quickstart/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[1]     at setFsWatchListener (/var/www/html/angular/quickstart/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/var/www/html/angular/quickstart/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleDir (/var/www/html/angular/quickstart/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:407:19)
[1]     at FSWatcher.<anonymous> (/var/www/html/angular/quickstart/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:455:19)
[1]     at FSWatcher.<anonymous> (/var/www/html/angular/quickstart/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:460:16)
[1]     at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by filipesilva** [comment]
`ENOSPC` means there is no space in the drive. Perhaps you are running low on disk space and the files cannot be created.
