### ISSUE TITLE
Unable to start Angular QuickStart seed

### ISSUE THREAD

**Issue by navroop** [angular/quickstart#334]
I have done npm install and when i run npm start get below error.

$ npm start

> angular-quickstart@1.0.0 start D:\angular2quickstart\quickstart
> tsc && concurrently "tsc -w" "lite-server"

 Error occured when executing command: tsc -w
 Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAG env variable.
     at detectExecuteFlag (D:\angular2quickstart\quickstart\node_modules\spawn-default-shell\src\get-shell.js:29:9)
     at getShell (D:\angular2quickstart\quickstart\node_modules\spawn-default-shell\src\get-shell.js:37:18)
     at Object.spawn (D:\angular2quickstart\quickstart\node_modules\spawn-default-shell\src\index.js:5:24)
     at D:\angular2quickstart\quickstart\node_modules\concurrently\src\main.js:192:34
     at arrayMap (D:\angular2quickstart\quickstart\node_modules\lodash\lodash.js:660:23)
     at Function.map (D:\angular2quickstart\quickstart\node_modules\lodash\lodash.js:9556:14)
     at run (D:\angular2quickstart\quickstart\node_modules\concurrently\src\main.js:181:22)
     at main (D:\angular2quickstart\quickstart\node_modules\concurrently\src\main.js:61:5)
     at Object.<anonymous> (D:\angular2quickstart\quickstart\node_modules\concurrently\src\main.js:421:1)
     at Module._compile (module.js:571:32)
     at Object.Module._extensions..js (module.js:580:10)
     at Module.load (module.js:488:32)
     at tryModuleLoad (module.js:447:12)
     at Function.Module._load (module.js:439:3)
     at Module.runMain (module.js:605:10)
     at run (bootstrap_node.js:420:7)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nsin13\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.3.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\angular2quickstart\quickstart\npm-debug.log

**Comment by filipesilva** [comment]
Heya, can you see if https://github.com/kimmobrunfeldt/concurrently/issues/71 helps? This seems to be a problem with some shell setups on a lib we use (`concurrently`).

**Comment by navroop** [comment]
thanks filipsilva for the reply, Got the issue at my end. there was environment variable Shell which was making problem...

**Comment by filipesilva** [comment]
Glad to hear it's working for you now!
