### ISSUE TITLE
Doesn't seem to work when using Bash for Windows

### ISSUE THREAD

**Issue by Imamadmad** [angular/quickstart#345]
I'm following the instructions at https://angular.io/docs/ts/latest/guide/setup.html to set up Angular2 for the first time locally and, after cloning this repo and not modifying any of the files, and `npm install`ing, I can't `npm start`.  I've updated both node and npm and it's still not working. I don't know if this is a problem with quickstart or if it's _Bash for Windows_ disagreeing with npm, but this code isn't working at all on my machine as cloned.

Full error message as follows:
```
$ npm start

> angular-quickstart@1.0.0 start /mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart
> tsc && concurrently "tsc -w" "lite-server"

[0] fs.js:1307
[0]     throw error;
[0]     ^
[0]
[0] Error: watch /mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart EPERM
[0]     at exports._errnoException (util.js:1022:11)
[0]     at FSWatcher.start (fs.js:1305:19)
[0]     at Object.fs.watch (fs.js:1330:11)
[0]     at Object.watchDirectory (/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/typescript/lib/tsc.js:1727:32)
[0]     at Object.executeCommandLine (/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/typescript/lib/tsc.js:39774:43)
[0]     at Object.<anonymous> (/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/typescript/lib/tsc.js:40095:4)
[0]     at Module._compile (module.js:571:32)
[0]     at Object.Module._extensions..js (module.js:580:10)
[0]     at Module.load (module.js:488:32)
[0]     at tryModuleLoad (module.js:447:12)
[0] tsc -w exited with code 1
[1] /mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/dev-ip/lib/dev-ip.js:21
[1]     var networkInterfaces = require("os").networkInterfaces();
[1]                                           ^
[1]
[1] Error: EINVAL: invalid argument, uv_interface_addresses
[1]     at getIp (/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/dev-ip/lib/dev-ip.js:21:43)
[1]     at Object.<anonymous> (/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/browser-sync/lib/utils.js:4:38)
[1]     at Module._compile (module.js:571:32)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:488:32)
[1]     at tryModuleLoad (module.js:447:12)
[1]     at Function.Module._load (module.js:439:3)
[1]     at Module.require (module.js:498:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/browser-sync/lib/snippet.js:9:20)
[1] lite-server exited with code 1

npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/npm-debug.log
```

...and npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'lite' ]
2 info using npm@4.0.5
3 info using node@v7.2.1
4 verbose run-script [ 'prelite', 'lite', 'postlite' ]
5 info lifecycle angular-quickstart@1.0.0~prelite: angular-quickstart@1.0.0
6 silly lifecycle angular-quickstart@1.0.0~prelite: no script for prelite, continuing
7 info lifecycle angular-quickstart@1.0.0~lite: angular-quickstart@1.0.0
8 verbose lifecycle angular-quickstart@1.0.0~lite: unsafe-perm in lifecycle true
9 verbose lifecycle angular-quickstart@1.0.0~lite: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle angular-quickstart@1.0.0~lite: CWD: /mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart
11 silly lifecycle angular-quickstart@1.0.0~lite: Args: [ '-c', 'lite-server' ]
12 silly lifecycle angular-quickstart@1.0.0~lite: Returned: code: 1  signal: null
13 info lifecycle angular-quickstart@1.0.0~lite: Failed to exec lite script
14 verbose stack Error: angular-quickstart@1.0.0 lite: `lite-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-quickstart@1.0.0
16 verbose cwd /mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart
17 error Linux 3.4.0+
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lite"
19 error node v7.2.1
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error angular-quickstart@1.0.0 lite: `lite-server`
22 error Exit status 1
23 error Failed at the angular-quickstart@1.0.0 lite script 'lite-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     lite-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by wardbell** [comment]
Don't know why and can't tell from this info.  Appears to be dying in the typescript watching (the first task in `npm start`).  Does `npm run tsc` work?

FWIW, I just followed the steps from scratch w/o a problem.

May just be a failed `npm install`. You might clear the decks and try again.  If it still happens, open a new issue with information about your environment including OS, node version, npm version.

**Comment by Foxandxss** [comment]
I do know. Bash for Windows doesn't support networking, so servers won't work

**Comment by Imamadmad** [comment]
@Foxandxss Ah damn, that's probably it.  Ran tsc and lite separately  and it was the latter that failed.  Any point adding a note to the README pointing out that this won't yet work on _Bash for Windows_, since this is the first instruction in the Angular2 how-to guide?

For reference, the output of `npm run lite`:
```
$ npm run lite

> angular-quickstart@1.0.0 lite /mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart
> lite-server

/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/dev-ip/lib/dev-ip.js:21
    var networkInterfaces = require("os").networkInterfaces();
                                          ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at getIp (/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/dev-ip/lib/dev-ip.js:21:43)
    at Object.<anonymous> (/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/browser-sync/lib/utils.js:4:38)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/node_modules/browser-sync/lib/snippet.js:9:20)

npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lite"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 lite: `lite-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 lite script 'lite-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lite-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/Madeleine/OneDrive/Documents/Web Stuff/quickstart/npm-debug.log
```

**Comment by wardbell** [comment]
Added warning to QuickStart Seed and to Setup Guide in [angular.io PR #3065](https://github.com/angular/angular.io/pull/3065)

**Comment by ibqn** [comment]
@Foxandxss where do you have this information from, any reference? Last time I have tried, it worked perfectly on Windows 10, with [Git bash](https://git-for-windows.github.io/)

**Comment by Foxandxss** [comment]
@ibqn git bash is one thing, Bash for Windows is a completely different beast.

Git bash is just a bash that comes with the git installation. Bash for Windows brings the linux ecosystem oficially to windows and it is like a more "native" solution.

Their current support for features is completely different.

**Comment by ibqn** [comment]
@wardbell Your sentence in README is sadly quite contra-productive and confusing, please provide a reference and what is exactly meant by _Bash for Windows_ as there are multiple ways to get bash prompt in windows.

**Comment by Foxandxss** [comment]
@ibqn It is not. There is something called "Bash for Windows" literally. It is not the concept of "there is a bash for windows" like gitbash as you said, it is a tool called like that.

https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by ibqn** [comment]
@Foxandxss I strongly disagree here, there is nothing I can see from the reference which you have provided literally called "Bash for Windows".  The thing you are referent to is called "Windows subsystem for Linux" which is quite new and still considered as a beta technology! This beta feature is based on ubuntu and that is why for short sometimes one can see references to bash prompt as "bash on ubuntu on windows".

There are multiple ways to have a working bash environment on windows which exist since decades.

That is why wording like "Bash for Windows" is not unique and thus very confusing, unless it is clearly stated which technology is used to provide bash.

**Comment by Foxandxss** [comment]
Yes, you speak the truth, but is also true that when people talks about WSL, they refer to it as _Bash for/on Windows_ (see OP). When they talk about git bash, they say gitbash.

If you want to change `Bash for Windows` to `Windows subsystem for Linux` on the readme, feel free to open a PR.
