### ISSUE TITLE
 Error occured when executing command: tsc -w  Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAG env variable.

### ISSUE THREAD

**Issue by peterhoang064** [angular/quickstart#359]
Hi, 
I got an error while execute npm start command on the windows 7 and I used git bash
Could you please help me. How to fix this issue ?
 Error occured when executing command: tsc -w
 Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAG env                                                                                                                 variable.
     at detectExecuteFlag (E:\xampp\htdocs\angular2\quickstart\node_modules\spaw                                                                                                                n-default-shell\src\get-shell.js:29:9)
     at getShell (E:\xampp\htdocs\angular2\quickstart\node_modules\spawn-default                                                                                                                -shell\src\get-shell.js:37:18)
     at Object.spawn (E:\xampp\htdocs\angular2\quickstart\node_modules\spawn-def                                                                                                                ault-shell\src\index.js:5:24)
     at E:\xampp\htdocs\angular2\quickstart\node_modules\concurrently\src\main.j                                                                                                                s:192:34
     at arrayMap (E:\xampp\htdocs\angular2\quickstart\node_modules\lodash\lodash                                                                                                                .js:660:23)

**Comment by alfian777** [comment]
Hi i run to similar issue with you. 

While i'm not sure how to properly fix this issue but let me share my workaround.

First.
You may want to update your SHELL env var by pointing it to your git bash location.
` export SHELL="/c/Program Files/Git/bin/bash" `
change the path to where your git bash location.

If up until this point you succeed then no need to change anything else. If not (I'm not). Then there is a problem in path resolve process. when you look deep inside spawn-default-shell Node Modules they are trying to compare our SHELL path with common shell regex.
`const DETECT_SH_REGEX = /sh$/;`
that variable assume that all shell name must end with "sh" while in our case it turns out to be 
`C:\Program Files\Git\bin\bash.exe`
which means ends with "sh.exe" then it trows an error. 

so the solution is change 
`const DETECT_SH_REGEX = /sh$/;`
to 
`const DETECT_SH_REGEX = /sh/;`

Hope that helps, pardon me if i wrongly explain something.

**Comment by GlenHerman** [comment]
alfian, thanks, this fixed it for me.

**Comment by sushilpatil123** [comment]
Hi Muhammad, I am trying the npm start command on cmd (Windows 8.1) but i still getting same error.
Please can you help me with this issue?

> angular-quickstart@1.0.0 start C:\quickstart-master\quickstart-master
> concurrently "npm run build:watch" "npm run serve"

 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1026:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:359:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:394:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:509:3
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1026:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:359:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:394:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:509:3
[1] npm run serve exited with code -4058

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "start"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "np
m run serve"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build:watch" "npm run serve"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\quickstart-master\quickstart-master\npm-debug.log

**Comment by kaykie** [comment]
anyone can help

**Comment by adechanterac** [comment]
Same issue but with node v6.10.2 and npm V3.10.10

**Comment by johanperezbb** [comment]
Hi alfian777, thank you so much. It worked for me too.

**Comment by oche-omale** [comment]
Thanks alfian777.

**Comment by Mgotya** [comment]
Thanks alfian777.

**Comment by connect2satyam** [comment]
Wow, Awesome it worked for me .
Note : Changes are not updating automatically on browser. 
I need to manually update the browser .

**Comment by senenkovitalik** [comment]
Thank

**Comment by AnshulMehta187** [comment]
It worked ,thanks

**Comment by JZiemnicki** [comment]
Thank you Alfian777. This worked for me as well.
