### ISSUE TITLE
Error: watch ENOSPC after npm start

### ISSUE THREAD

**Issue by fabioperrella** [angular/quickstart#37]
Hi, I'm getting this error after npm start:
```
npm start

> angular2-quickstart@1.0.0 start /home/fabio/workspace/github/quickstart
> concurrently "npm run tsc:w" "npm run lite" 

[1] 
[1] > angular2-quickstart@1.0.0 lite /home/fabio/workspace/github/quickstart
[1] > lite-server
[1] 
[0] 
[0] > angular2-quickstart@1.0.0 tsc:w /home/fabio/workspace/github/quickstart
[0] > tsc -w
[0] 
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync options **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[1] [BS] Access URLs:
[1]  --------------------------------------
[1]        Local: http://localhost:3000
[1]     External: http://192.168.1.103:3000
[1]  --------------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://192.168.1.103:3001
[1]  --------------------------------------
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] 16.03.19 17:35:49 304 GET /index.html
[1] 16.03.19 17:35:51 304 GET /styles.css
[1] 16.03.19 17:35:51 304 GET /node_modules/es6-shim/es6-shim.min.js
[1] 16.03.19 17:35:51 304 GET /node_modules/systemjs/dist/system-polyfills.js
[1] 16.03.19 17:35:51 304 GET /node_modules/angular2/es6/dev/src/testing/shims_for_IE.js
[1] 16.03.19 17:35:51 304 GET /node_modules/angular2/bundles/angular2-polyfills.js
[1] 16.03.19 17:35:51 304 GET /node_modules/systemjs/dist/system.src.js
[0] 17:35:52 - Compilation complete. Watching for file changes.
[1] 16.03.19 17:35:52 304 GET /node_modules/rxjs/bundles/Rx.js
[1] 16.03.19 17:35:52 304 GET /node_modules/angular2/bundles/angular2.dev.js
[1] [BS] File changed: app/app.component.js
[1] [BS] File changed: app/main.js
[1] 16.03.19 17:35:54 200 GET /app/main.js
[1] 16.03.19 17:35:54 200 GET /app/app.component.js
[1] 
[1] events.js:72
[1]         throw er; // Unhandled 'error' event
[1]               ^
[1] Error: watch ENOSPC
[1]     at errnoException (fs.js:1024:11)
[1]     at FSWatcher.start (fs.js:1056:11)
[1]     at Object.fs.watch (fs.js:1081:11)
[1]     at createFsWatchInstance (/home/fabio/workspace/github/quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[1]     at setFsWatchListener (/home/fabio/workspace/github/quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/fabio/workspace/github/quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleFile (/home/fabio/workspace/github/quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:255:21)
[1]     at FSWatcher.<anonymous> (/home/fabio/workspace/github/quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:473:21)
[1]     at Object.oncomplete (fs.js:107:15)
[1] npm
[1]  
[1] ERR! weird error 8
[1] npm
[1]  WARN This failure might be due to the use of legacy binary "node"
[1] npm
[1]  WARN For further explanations, please read
[1] /usr/share/doc/nodejs/README.Debian
[1]  
[1] npm
[1]  ERR! not ok code 0
[1] npm run lite exited with code 1
```

**Comment by wardbell** [comment]
dup of #35
