### ISSUE TITLE
Sudden error in npm run build at tsc -p src/

### ISSUE THREAD

**Issue by rfball** [angular/quickstart#376]
I am using version 0.2.22 (2017-01-05). Everything just fine until about 1 hour ago then get an error in npm run build at tsc -p src/ 

debug log:

13 info lifecycle angular-quickstart@1.0.0~build: Failed to exec build script
14 verbose stack Error: angular-quickstart@1.0.0 build: `tsc -p src/`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-quickstart@1.0.0
16 verbose cwd C:\Users\rball\Documents\Dev\Angular\quickstart
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v7.1.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error angular-quickstart@1.0.0 build: `tsc -p src/`
22 error Exit status 2

**Comment by rfball** [comment]
I finally figured out what happened.  I had mixed template driven forms and model driven forms between the html and the component. Too bad there is not more information in the stack trace.
