### ISSUE TITLE
node_modules files are not excluded; BrowserSync not working

### ISSUE THREAD

**Issue by mpduffey** [angular/quickstart#38]
When loading the angular2-quickstart module onto an AWS Amazon Linux AMI 2015.09.2 (HVM), SSD Volume Type, I have installed:
1) node.js v5.9.0
2) npm v3.8.2
3) git v2.4.3

I cloned the angular-quickstart repo into the home directory and ran npm install.

The tsconfig.json from angular2/quickstart lists "node_modules" in the "exclude" property, as follows:
{
	"compilerOptions": {
		"target": "es5",
		"module": "system",
		"moduleResolution": "node",
		"sourceMap": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"removeComments": false,
		"noImplicitAny": false
	},
	"exclude": [
		"node_modules",
		"typings/main",
		"typings/main.d.ts"
	]
}

**Despite this, when I run npm start, several files from the node_modules directory are listed as containing errors, as seen in the terminal output below. In addition, the BrowserSync option that refreshes the page following file changes does not execute when files are changed.**

> angular2-quickstart@1.0.0 start /home/quickstart
> concurrently "npm run tsc:w" "npm run lite" 

[0]
[0] > angular2-quickstart@1.0.0 tsc:w /home/quickstart
[0] > tsc -w
[0]
[1]
[1] > angular2-quickstart@1.0.0 lite /home/quickstart
[1] > lite-server
[1]
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync options **
[1] { injectChanges: false, 
[1] files: [ './**/*.{html,htm,css,js}' ],
[1] server: { baseDir: './', middleware: [ [Function], [Function] ] } } 
[1] [BS] Access URLs: 
[1]-----------------------------------
[1]Local: http://localhost:3000 
[1] External: http://10.0.3.253:3000
[1]-----------------------------------
[1] UI: http://localhost:3001 
[1]UI External: http://10.0.3.253:3001
[1]-----------------------------------
[1] [BS] Serving files from: ./ 
[1] [BS] Watching files...
[0] node_modules/angular2/src/core/application_ref.d.ts(96,147): error TS2304: Cannot find name 'Promise'.
[0] node_modules/angular2/src/core/application_ref.d.ts(133,90): error TS2304: Cannot find name 'Promise'.
[0] node_modules/angular2/src/core/application_ref.d.ts(171,81): error TS2304: Cannot find name 'Promise'.
[0] node_modules/angular2/src/core/change_detection/differs/default_keyvalue_differ.d.ts(23,15): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/core/change_detection/differs/default_keyvalue_differ.d.ts(25,16): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/core/change_detection/parser/locals.d.ts(3,14): error TS2304: Cannot find name 'Map'. 
[0] node_modules/angular2/src/core/change_detection/parser/locals.d.ts(4,42): error TS2304: Cannot find name 'Map'. 
[0] node_modules/angular2/src/core/debug/debug_node.d.ts(14,13): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/core/debug/debug_node.d.ts(24,17): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/core/debug/debug_node.d.ts(25,17): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/core/di/provider.d.ts(436,103): error TS2304: Cannot find name 'Map'. 
[0] node_modules/angular2/src/core/di/provider.d.ts(436,135): error TS2304: Cannot find name 'Map'. 
[0] node_modules/angular2/src/core/linker/compiler.d.ts(12,50): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/core/linker/compiler.d.ts(16,41): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(108,136): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(156,150): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(197,128): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(203,127): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(204,141): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(205,119): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/core/render/api.d.ts(13,13): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/core/render/api.d.ts(14,84): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
[0] node_modules/angular2/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
[0] node_modules/angular2/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'. 
[0] node_modules/angular2/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'. 
[0] node_modules/angular2/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'. 
[0] node_modules/angular2/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'. 
[0] node_modules/angular2/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'. 
[0] node_modules/angular2/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'. 
[0] node_modules/angular2/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'. 
[0] node_modules/angular2/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'. 
[0] node_modules/angular2/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
[0] node_modules/angular2/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
[0] node_modules/angular2/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
[0] node_modules/angular2/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
[0] node_modules/angular2/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
[0] node_modules/angular2/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/angular2/src/platform/browser/browser_adapter.d.ts(75,33): error TS2304: Cannot find name 'Map'. 
[0] node_modules/angular2/src/platform/dom/dom_adapter.d.ts(85,42): error TS2304: Cannot find name 'Map'. 
[0] node_modules/rxjs/CoreOperators.d.ts(35,67): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/CoreOperators.d.ts(50,66): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/CoreOperators.d.ts(89,67): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/CoreOperators.d.ts(94,38): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/CoreOperators.d.ts(94,50): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/Observable.d.ts(46,62): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/rxjs/Observable.d.ts(47,42): error TS2304: Cannot find name 'Iterator'.
[0] node_modules/rxjs/Observable.d.ts(103,74): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/Observable.d.ts(103,84): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/Observable.d.ts(143,66): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/Observable.d.ts(158,65): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/Observable.d.ts(201,66): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/Observable.d.ts(206,38): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/Observable.d.ts(206,50): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/observable/ForkJoinObservable.d.ts(6,50): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/rxjs/observable/ForkJoinObservable.d.ts(7,58): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/rxjs/observable/FromObservable.d.ts(7,38): error TS2304: Cannot find name 'Promise'. 
[0] node_modules/rxjs/observable/FromObservable.d.ts(7,51): error TS2304: Cannot find name 'Iterator'.
[0] node_modules/rxjs/observable/PromiseObservable.d.ts(9,31): error TS2304: Cannot find name 'Promise'.
[0] node_modules/rxjs/observable/PromiseObservable.d.ts(10,26): error TS2304: Cannot find name 'Promise'. 
[0] 12:49:34 AM - Compilation complete. Watching for file changes.

**Comment by Foxandxss** [comment]
Seems like you don't have the typings installed there.

**Comment by mpduffey** [comment]
@Foxandxss  - that appears to have done it. I ran "sudo npm run postinstall" and it installed typings, and server starts do not list out the node_modules files. I wonder why npm did not run the postinstall following npm install?

**Comment by mpduffey** [comment]
**I have run into another issue with the same configuration above. When running npm start, I now receive the following errors:
**
> angular2-quickstart@1.0.0 start /home/ng2-master-app
> concurrently "npm run tsc:w" "npm run lite" 

[1] 
[1] > angular2-quickstart@1.0.0 lite /home/ng2-master-app 
[1] > lite-server 
[1] 
[0] 
[0] > angular2-quickstart@1.0.0 tsc:w /home/ng2-master-app
[0] > tsc -w
[0] 
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync options **
[1] { injectChanges: false, 
[1] files: [ './**/*.{html,htm,css,js}' ],
[1] server: { baseDir: './', middleware: [ [Function], [Function] ] } } 
[0] app/components/autocomplete/autocomplete.ts(8,14): error TS1005: '(' expected.
[1] [BS] Access URLs: 
[1]---------------------------------- 
[1]Local: http://localhost:3000 
[1] External: http://10.0.7.68:3000 
[1]---------------------------------- 
[1] UI: http://localhost:3001 
[1]UI External: http://10.0.7.68:3001 
[1]---------------------------------- 
[1] [BS] Serving files from: ./ 
[1] [BS] Watching files...
[0] 2:06:12 AM - Compilation complete. Watching for file changes. 
[1] [BS] File changed: app/app.component.js 
[1] [BS] File changed: app/main.js
[1] events.js:154 
[1] throw er; // Unhandled 'error' event
[1] ^ 
[1] 
[1] Error: watch node_modules/angular2/ts/examples/core/pipes/ts/async_pipe ENOSPC
[1] at exports._errnoException (util.js:890:11) 
[1] at FSWatcher.start (fs.js:1313:19)
[1] at Object.fs.watch (fs.js:1341:11)
[1] at createFsWatchInstance (/home/ng2-master-app/node_modules/chokidar/lib/nodefs-handler.js:37:15) 
[1] at setFsWatchListener (/home/ng2-master-app/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1] at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ng2-master-app/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1] at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ng2-master-app/node_modules/chokidar/lib/nodefs-handler.js:228:14) 
[1] at FSWatcher.NodeFsHandler._handleDir (/home/ng2-master-app/node_modules/chokidar/lib/nodefs-handler.js:407:19) 
[1] at FSWatcher.<anonymous> (/home/ng2-master-app/node_modules/chokidar/lib/nodefs-handler.js:455:19)
[1] at FSWatcher.<anonymous> (/home/ng2-master-app/node_modules/chokidar/lib/nodefs-handler.js:460:16)
[1] at FSReqWrap.oncomplete (fs.js:82:15) 
[1] 
[1] npm 
[1] 
[1] ERR!
[1]Linux 4.1.17-22.30.amzn1.x86_64
[1] npm 
[1] 
[1] ERR!
[1] 
[1] argv
[1]"/usr/bin/node" "/usr/bin/npm" "run" "lite"
[1] npm 
[1] 
[1] ERR! node v5.9.0
[1] npm ERR! npm
[1]v3.8.2 
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! angular2-quickstart@1.0.0 lite: `lite-server`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the angular2-quickstart@1.0.0 lite script 'lite-server'. 
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the angular2-quickstart package, 
[1] npm ERR! not with npm itself. 
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR! lite-server
[1] npm ERR! You can get information on how to open an issue for this project with: 
[1] npm ERR! npm bugs angular2-quickstart 
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR! npm owner ls angular2-quickstart 
[1] npm ERR! There is likely additional logging output above. 
[1] 
[1] npm 
[1] 
[1] ERR!
[1]Please include the following file with any support request:
[1] npm 
[1] 
[1] ERR!
[1]/home/ng2-master-app/npm-debug.log 
[1] npm run lite exited with code 1

**Comment by mpduffey** [comment]
Corrected with this solution: http://stackoverflow.com/questions/34372851/angular-2-quickstart-enospc-error
