### ISSUE TITLE
Something wrong on Raspberry Pi 's official OS: Rasbian

### ISSUE THREAD

**Issue by liuxue0905** [angular/quickstart#382]
OS:
Raspberry Pi 's official OS: Rasbian

NodeJS:
[Installing Node.js via package manager](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)
Debian and Ubuntu based Linux distributions
armhf (ARM 32-bit hard-float, ARMv7 and up: arm-linux-gnueabihf)

node version: 7.5.0
npm version: 4.1.2

Git:
Then, I git clone angular quickstart
and `npm install`
last `npm start`

Error Log:
````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle GoldenTimes-front-end@1.0.0~prestart: GoldenTimes-front-end@1.0.0
6 verbose lifecycle GoldenTimes-front-end@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle GoldenTimes-front-end@1.0.0~prestart: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/Downloads/GoldenTimes/GoldenTimes-front-end/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
8 verbose lifecycle GoldenTimes-front-end@1.0.0~prestart: CWD: /home/pi/Downloads/GoldenTimes/GoldenTimes-front-end
9 silly lifecycle GoldenTimes-front-end@1.0.0~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle GoldenTimes-front-end@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle GoldenTimes-front-end@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: GoldenTimes-front-end@1.0.0 prestart: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:192:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:192:7)
12 verbose stack     at maybeClose (internal/child_process.js:890:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid GoldenTimes-front-end@1.0.0
14 verbose cwd /home/pi/Downloads/GoldenTimes/GoldenTimes-front-end
15 error Linux 4.4.11-v7+
16 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
17 error node v7.5.0
18 error npm  v4.1.2
19 error code ELIFECYCLE
20 error GoldenTimes-front-end@1.0.0 prestart: `npm run build`
20 error Exit status 1
21 error Failed at the GoldenTimes-front-end@1.0.0 prestart script 'npm run build'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the GoldenTimes-front-end package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run build
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs GoldenTimes-front-end
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls GoldenTimes-front-end
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
````

**Comment by liuxue0905** [comment]
I reset all of things, it will work well.
