### ISSUE TITLE
#3rd party component using module.id throws Error: (SystemJS) module is not defined

### ISSUE THREAD

**Issue by luis-cortina** [angular/quickstart#422]
Hi:

I saw john papa's comment on this thread https://github.com/systemjs/systemjs/issues/1266#issuecomment-218442312 and I'm having a similar issue with the latest version of the quickstart template.

I have a 3rd party component that is using 
```
moduleId: module.id,
```
 and I have to comment that out to make it run, otherwise I get an error like this:

```
Error: (SystemJS) module is not defined
	ReferenceError: module is not defined
	    at eval (http://localhost:3000/node_modules/clarity-angular/clarity-angular.umd.js:5964:31)
	    at Object.eval (http://localhost:3000/node_modules/clarity-angular/clarity-angular.umd.js:6005:2)
	    at Object.eval (http://localhost:3000/app/app.module.js:10:25)
	    at eval (http://localhost:3000/app/app.module.js:32:4)
	    at eval (http://localhost:3000/app/app.module.js:33:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/main.js
	Error loading http://localhost:3000/main.js
	    at eval (http://localhost:3000/node_modules/clarity-angular/clarity-angular.umd.js:5964:31)
	    at Object.eval (http://localhost:3000/node_modules/clarity-angular/clarity-angular.umd.js:6005:2)
	    at Object.eval (http://localhost:3000/app/app.module.js:10:25)
	    at eval (http://localhost:3000/app/app.module.js:32:4)
	    at eval (http://localhost:3000/app/app.module.js:33:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/main.js
	Error loading http://localhost:3000/main.js
```

Any idea what I'm I missing here?

Thanks in advance,

Luis

**Comment by Foxandxss** [comment]
Interesting. I will upload a fix in the next few days. A quick fix (well, what I am going to do) is to open the systemjs-angular-loader and on the top, add something like

`if (load.source.indexOf('moduleId') != -1) return;`

That should fix it.
