### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by agopali** [angular/quickstart#426]
npm start not working and getting following errors:

> angular-quickstart@1.0.0 prestart C:\quickstart\quickstart-master
> npm run build
> angular-quickstart@1.0.0 build C:\quickstart\quickstart-master
> tsc -p src/
> angular-quickstart@1.0.0 start C:\quickstart\quickstart-master
> concurrently "npm run build:watch" "npm run serve"
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1018:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:393:7)
     at startup (bootstrap_node.js:150:9)
     at bootstrap_node.js:508:3
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1018:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:393:7)
     at startup (bootstrap_node.js:150:9)
     at bootstrap_node.js:508:3
[1] npm run serve exited with code -4058

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "np
m run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm
run build:watch" "npm run serve"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart pa
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build:watch" "npm run serve"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\quickstart\quickstart-master\npm-debug.log

solutions will be appreciated.

**Comment by agopali** [comment]
issue has been moved to #16237
