### ISSUE TITLE
Uncaught (in promise): Error: Error: Unexpected directive value '[object Object]' on the View of component 'HomeComponent'

### ISSUE THREAD

**Issue by uma075** [angular/quickstart#427]
Facing this error, I am using angular 2.0.0-rc.4.
Please help.
Error:

localhost/:30 Error: Error: Unexpected directive value '[object Object]' on the View of component 'HomeComponent'
	    at new BaseException (http://localhost:56580/node_modules/@angular/compiler/src/facade/exceptions.js:27:23)
	    at CompileMetadataResolver.getViewDirectivesMetadata (http://localhost:56580/node_modules/@angular/compiler/src/metadata_resolver.js:227:23)
	    at RuntimeCompiler._getCompiledTemplate (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:99:36)
	    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:117:80)
	    at eval (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:120:77)
	    at Array.forEach (native)
	    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:120:41)
	    at RuntimeCompiler.compileComponentAsync (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:43:30)
	    at RuntimeCompiler.resolveComponent (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:39:21)
	    at eval (http://localhost:56580/node_modules/@angular/core/src/application_ref.js:165:37)
	Evaluating http://localhost:56580/app/home.js
	Error loading http://localhost:56580/app/home.js
(anonymous) @ localhost/:30
zone.js:388 Unhandled Promise rejection: Error: Unexpected directive value '[object Object]' on the View of component 'HomeComponent'
	    at new BaseException (http://localhost:56580/node_modules/@angular/compiler/src/facade/exceptions.js:27:23)
	    at CompileMetadataResolver.getViewDirectivesMetadata (http://localhost:56580/node_modules/@angular/compiler/src/metadata_resolver.js:227:23)
	    at RuntimeCompiler._getCompiledTemplate (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:99:36)
	    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:117:80)
	    at eval (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:120:77)
	    at Array.forEach (native)
	    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:120:41)
	    at RuntimeCompiler.compileComponentAsync (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:43:30)
	    at RuntimeCompiler.resolveComponent (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:39:21)
	    at eval (http://localhost:56580/node_modules/@angular/core/src/application_ref.js:165:37)
	Evaluating http://localhost:56580/app/home.js
	Error loading http://localhost:56580/app/home.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Unexpected directive value '[object Object]' on the View of component 'HomeComponent'
	    at new BaseException (http://localhost:56580/node_modules/@angular/compiler/src/facade/exceptions.js:27:23)
	    at CompileMetadataResolver.getViewDirectivesMetadata (http://localhost:56580/node_modules/@angular/compiler/src/metadata_resolver.js:227:23)
	    at RuntimeCompiler._getCompiledTemplate (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:99:36)
	    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:117:80)
	    at eval (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:120:77)
	    at Array.forEach (native)
	    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:120:41)
	    at RuntimeCompiler.compileComponentAsync (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:43:30)
	    at RuntimeCompiler.resolveComponent (http://localhost:56580/node_modules/@angular/compiler/src/runtime_compiler.js:39:21)
	    at eval (http://localhost:56580/node_modules/@angular/core/src/application_ref.js:165:37)
	Evaluating http://localhost:56580/app/home.js
	Error loading http://localhost:56580/app/home.js null

Component:
import { Component, ViewContainerRef } from '@angular/core';
import { Routes, ROUTER_DIRECTIVES, ROUTER_PROVIDERS } from '@angular/router';
import { AppServiceHome } from '../../services/app.service.home';
import { AppHeader } from '../../components/app.header/app.header';
import { AppFooter } from '../../components/app.footer/app.footer';
import { AppMainPage } from '../../components/main-page/main-page';
import { JoinPage } from '../../components/join-page/join-page';
@Component({
    selector: 'home-page',
    template: '<app-header></app-header><router-outlet></router-outlet><app-footer></app-footer>',
    directives: [AppHeader, Routes, ROUTER_DIRECTIVES, ROUTER_PROVIDERS, AppFooter, AppMainPage]
})

@Routes([
    { path: '', component: AppMainPage },
    { path: '/', component: AppMainPage },
    { path: '/join', component: JoinPage }
])

//@RouteConfig([
//    { path: '', name: 'main-page', component: AppMainPage, useAsDefault: true },
//    { path: '/', name: 'main-page', component: AppMainPage },
//    { path: '/join', name: 'join-page', component: JoinPage }
//])

export class HomeComponent {

}

Package JSON:
{
  "name": "aspnet",
  "version": "0.0.0",
  "scripts": {
    "postinstall": "typings install",
    "typings": "typings"
  },
  "license": "ISC",
  "devDependencies": {
    "typings": "0.8.1"
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "^2.0.0-rc.2",
    "@angular/router-deprecated": "^2.0.0-rc.2",
    "@azure-iot/configuration": "^1.0.0-rc.6",
    "@azure-iot/hal": "^1.0.0-rc.2",   
    "angular2-uuid": "^1.0.7",  
    "bootstrap": "^3.3.6",
    "compression": "^1.6.2",    
    "cors": "^2.7.1",
    "csurf": "^1.9.0",
    "debug": "^2.2.0",    
    "es5-shim": "^4.5.0",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",    
    "json-2-csv": "^2.0.18",
    "log4js": "^0.6.38",
    "markdown-it": "^8.2.1",    
    "ng2-bootstrap": "1.0.24",
    "ng2-cookies": "^1.0.2",
    "ng2-file-upload": "1.0.3",
    "node-uuid": "^1.4.7",    
    "reflect-metadata": "0.1.2",
    "request": "^2.72.0",
    "rxjs": "5.0.0-beta.6",
    "sanitize-html": "1.13.0",
    "sendgrid": "^4.0.1",
    "systemjs": "^0.19.27",
    "tsd": "^0.6.5",
    "underscore": "^1.8.3",
    "zone.js": "^0.6.12",
    "@angular/upgrade": "2.0.0-rc.4",
    "core-js": "^2.4.0",
    "angular2-in-memory-web-api": "0.0.9"
  }
}

**Comment by uma075** [comment]
Issue resolve on deleting @Angular/Router as There were two modules @Angular/Router and @Angular/Router-Depreciated. So something conflicted, deleted router module. Its working like charm.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
