### ISSUE TITLE
failed to install inside docker container

### ISSUE THREAD

**Issue by laurencefass** [angular/quickstart#428]
quickstart app failed to npm install inside docker container

environment info...
npm version: 4.2.0
node version: 7.8
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"

[standard npm install tasks....]

...

| `-- symbol-observable@1.0.4
+-- systemjs@0.19.40
| `-- when@3.7.8
+-- tslint@3.15.1
| +-- colors@1.1.2
| +-- diff@2.2.3
| +-- findup-sync@0.3.0
| | `-- glob@5.0.15
| `-- underscore.string@3.3.4
|   +-- sprintf-js@1.0.3
|   `-- util-deprecate@1.0.2
+-- typescript@2.1.6
`-- zone.js@0.8.5

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.57-boot2docker
npm ERR! argv "/root/.nvm/versions/node/v7.8.0/bin/node" "/root/.nvm/versions/node/v7.8.0/bin/npm" "install"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! path /home/vs1/public_html/quickstart/node_modules/.expand-braces.DELETE/node_modules/expand-range
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall rename

npm ERR! Error
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/install/action/finalize.js:68:7
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (/root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR!     at moveModules (/root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/install/action/finalize.js:65:5)
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/install/action/finalize.js:60:70
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/mkdirp/index.js:30:20
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename '/home/vs1/public_html/quickstart/node_modules/.expand-braces.DELETE/node_modules/expand-range' -> '/home/vs1/public_html/quickstart/node_modules/expand-braces/node_modules/expand-range'
npm ERR!  { Error
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/install/action/finalize.js:68:7
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (/root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR!     at moveModules (/root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/install/action/finalize.js:65:5)
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/install/action/finalize.js:60:70
npm ERR!     at /root/.nvm/versions/node/v7.8.0/lib/node_modules/npm/node_modules/mkdirp/index.js:30:20
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename '/home/vs1/public_html/quickstart/node_modules/.expand-braces.DELETE/node_modules/expand-range' -> '/home/vs1/public_html/quickstart/node_modules/expand-braces/node_modules/expand-range' parent: 'angular-quickstart' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-04-05T12_34_35_543Z-debug.log
root@7d79e0ef52d1:/home/vs1/public_html/quickstart#

**Comment by laurencefass** [comment]
this is a docker problem and works fine in non-mounted folders.
