### ISSUE TITLE
Initializers are not allowed in ambient contexts

### ISSUE THREAD

**Issue by ElenaOr** [angular/quickstart#451]
https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html
Install TypeScript 2.2 for Visual Studio 2015
It has  "spec": ">=2.2.0 <2.3.0",

But
Your quickstart source package.json:"typescript": "~2.1.0"

**Comment by martytheparty** [comment]
Thank you!  That fixed my problem :)

I followed the instructions at https://angular.io/docs/ts/latest/guide/webpack.html and in the package.json file they have:

"typescript": "~2.0.10",

I changed it to:

"typescript": "^2.2.0",

and the initializers not allowed in ambient contexts error when away.

Thank You!

**Comment by CindySLiu** [comment]
Now I include everything in quickstart-master, I still get the same error.

I saw .angular-cli.json included in quickstart-master. I tried ng serve and got the following error:

The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (C:\MyProjects\VS_Angular\WebApplication3\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\MyProjects\VS_Angular\WebApplication3\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

Can we also build the project via ng serve?

Thanks in advance!!!

**Comment by CindySLiu** [comment]
Fixed the issue. VS 2015 project file uses TypeScript 2.0 instead of 2.2.

**Comment by andrewh-pureprint** [comment]
Just did the same. Worked for me too. Thanks a lot.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
