### ISSUE TITLE
Running into issue with npm start

### ISSUE THREAD

**Issue by ADPangburn** [angular/quickstart#458]
I am trying to build my first angular 2 app and follow the tutorial and I am getting this when I try npm start

D:\Angular2\quickstart-master>npm start

> angular-quickstart@1.0.0 prestart D:\Angular2\quickstart-master
> npm run build

> angular-quickstart@1.0.0 build D:\Angular2\quickstart-master
> tsc -p src/

> angular-quickstart@1.0.0 start D:\Angular2\quickstart-master
> concurrently "npm run build:watch" "npm run serve"

D:\Angular2\quickstart-master\node_modules\concurrently\src\main.js:198
          spawnOpts.env = Object.assign({FORCE_COLOR: supportsColor.level}, pr
                                 ^
TypeError: undefined is not a function
    at D:\Angular2\quickstart-master\node_modules\concurrently\src\main.js:198:3
4
    at arrayMap (D:\Angular2\quickstart-master\node_modules\lodash\lodash.js:660
:23)
    at Function.map (D:\Angular2\quickstart-master\node_modules\lodash\lodash.js
:9571:14)
    at run (D:\Angular2\quickstart-master\node_modules\concurrently\src\main.js:
189:22)
    at main (D:\Angular2\quickstart-master\node_modules\concurrently\src\main.js
:61:5)
    at Object.<anonymous> (D:\Angular2\quickstart-master\node_modules\concurrent
ly\src\main.js:438:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "np
m run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm
run build:watch" "npm run serve"'.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build:watch" "npm run serve"
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Angular2\quickstart-master\npm-debug.log

Here is what log file has(I couldn't attach)

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart angular-quickstart@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info start angular-quickstart@1.0.0
9 verbose unsafe-perm in lifecycle true
10 info angular-quickstart@1.0.0 Failed to exec start script
11 verbose stack Error: angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
11 verbose stack Exit status 1
11 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:110:17)
11 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
11 verbose stack     at ChildProcess.emit (events.js:110:17)
11 verbose stack     at maybeClose (child_process.js:1015:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
12 verbose pkgid angular-quickstart@1.0.0
13 verbose cwd D:\Angular2\quickstart-master
14 error Windows_NT 6.3.9600
15 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
16 error node v0.12.2
17 error npm  v2.7.4
18 error code ELIFECYCLE
19 error angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
19 error Exit status 1
20 error Failed at the angular-quickstart@1.0.0 start script 'concurrently "npm run build:watch" "npm run serve"'.
20 error This is most likely a problem with the angular-quickstart package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     concurrently "npm run build:watch" "npm run serve"
20 error You can get their info via:
20 error     npm owner ls angular-quickstart
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]

**Comment by ADPangburn** [comment]
Was not running command line as administrator... lesson learned.
