### ISSUE TITLE
npm start not working on angular quickstart

### ISSUE THREAD

**Issue by moningisridhar** [angular/quickstart#460]
I have followed step by step, as said in the angular quickstart.

Using Windows 7.

While running npm start, I am getting below error:

 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1018:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:390:7)
     at startup (bootstrap_node.js:150:9)
     at bootstrap_node.js:505:3
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1018:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:390:7)
     at startup (bootstrap_node.js:150:9)
     at bootstrap_node.js:505:3
[1] npm run serve exited with code -4058
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\smoningi\AppData\Roaming\npm-cache\_logs\2017-05-23T09_31_58_597Z-debug.log

Please help me, to get rid of this.

**Comment by knitesh** [comment]
did you run npm install before running npm start

**Comment by MohammadRefaatMadkour** [comment]
i have the same error, and i install npm before running npm start

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)

**Comment by rafiqips5** [comment]
run below two commands will solve the problem in node command window

npm install rx-observable-update --save

npm install rxjs update 

to solve concurrent problem..

npm install -g concurrently
