### ISSUE TITLE
NPM run build fails exit status 2

### ISSUE THREAD

**Issue by whackdev** [angular/quickstart#468]
This originally worked for me, when I shutdown the initial instance to shut down my computer and then tried to run `npm start` again I get this error:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-quickstart@1.0.0~prestart: angular-quickstart@1.0.0
6 verbose lifecycle angular-quickstart@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle angular-quickstart@1.0.0~prestart: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/nick/Desktop/Angular_Quickstart/quickstart/node_modules/.bin:/home/nick/bin:/home/nick/.local/bin:/home/nick/bin:/home/nick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
8 verbose lifecycle angular-quickstart@1.0.0~prestart: CWD: /home/nick/Desktop/Angular_Quickstart/quickstart
9 silly lifecycle angular-quickstart@1.0.0~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle angular-quickstart@1.0.0~prestart: Returned: code: 2  signal: null
11 info lifecycle angular-quickstart@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: angular-quickstart@1.0.0 prestart: `npm run build`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:194:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:194:7)
12 verbose stack     at maybeClose (internal/child_process.js:899:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid angular-quickstart@1.0.0
14 verbose cwd /home/nick/Desktop/Angular_Quickstart/quickstart
15 error Linux 4.4.0-77-generic
16 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
17 error node v7.10.0
18 error npm  v4.2.0
19 error code ELIFECYCLE
20 error errno 2
21 error angular-quickstart@1.0.0 prestart: `npm run build`
21 error Exit status 2
22 error Failed at the angular-quickstart@1.0.0 prestart script 'npm run build'.
22 error Make sure you have the latest version of node.js and npm installed.
22 error If you do, this is most likely a problem with the angular-quickstart package,
22 error not with npm itself.
22 error Tell the author that this fails on your system:
22 error     npm run build
22 error You can get information on how to open an issue for this project with:
22 error     npm bugs angular-quickstart
22 error Or if that isn't available, you can get their info via:
22 error     npm owner ls angular-quickstart
22 error There is likely additional logging output above.
23 verbose exit [ 2, true ]

**Comment by whackdev** [comment]
I didn't get an answer but the new update fixed it.
