### ISSUE TITLE
Error in npm quick start 

### ISSUE THREAD

**Issue by harshapocharam** [angular/quickstart#478]
i had installed npm and tried to execute npm start cmd and i got following error!

  Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1018:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:389:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:504:3
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1018:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:606:11)
     at run (bootstrap_node.js:389:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:504:3
[1] npm run serve exited with code -4058
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
.npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Harsha\AppData\Roaming\npm-cache\_logs\2017-07-07T21_06_20_028Z-debug.log

please help me out in fixing this problem 
thank you in advance

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
