### ISSUE TITLE
Traceur not found

### ISSUE THREAD

**Issue by CindySLiu** [angular/quickstart#481]
Following quickstart, resolved all compilation errors. When running the index.html in browser, I got "traceur not found" error. Anyone has any idea?

Thanks in advance!!!

zone.js:2616 GET http://localhost:53423/traceur 404 (Not Found)
scheduleTask @ zone.js:2616
ZoneDelegate.scheduleTask @ zone.js:410
Zone.scheduleTask @ zone.js:235
Zone.scheduleMacroTask @ zone.js:258
(anonymous) @ zone.js:2640
proto.(anonymous function) @ zone.js:1221
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:847
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:141
(anonymous) @ zone.js:831
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:191
drainMicroTaskQueue @ zone.js:595
ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1364
globalZoneAwareCallback @ zone.js:1382
index.html:18 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:53423/traceur
	Error: XHR error (404 Not Found) loading http://localhost:53423/traceur
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:53423/node_modules/zone.js/dist/zone.js:1069:39)
	    at ZoneDelegate.invokeTask (http://localhost:53423/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:53423/node_modules/zone.js/dist/zone.js:191:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:53423/node_modules/zone.js/dist/zone.js:498:34)
	    at invokeTask (http://localhost:53423/node_modules/zone.js/dist/zone.js:1364:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:53423/node_modules/zone.js/dist/zone.js:1382:17)
	Error loading http://localhost:53423/traceur
	Unable to load transpiler to transpile http://localhost:53423/app/main.js
	Error loading http://localhost:53423/app/main.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:53423/node_modules/zone.js/dist/zone.js:1069:39)
	    at ZoneDelegate.invokeTask (http://localhost:53423/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:53423/node_modules/zone.js/dist/zone.js:191:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:53423/node_modules/zone.js/dist/zone.js:498:34)
	    at invokeTask (http://localhost:53423/node_modules/zone.js/dist/zone.js:1364:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:53423/node_modules/zone.js/dist/zone.js:1382:17)
	Error loading http://localhost:53423/traceur
	Unable to load transpiler to transpile http://localhost:53423/app/main.js
	Error loading http://localhost:53423/app/main.js

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
