### ISSUE TITLE
npm run serve exited with code -4058 on working with Quickstart.

### ISSUE THREAD

**Issue by atul-609** [angular/quickstart#483]
npm run serve exited with code -4058 on working with Quickstart..
I've just started working on angular2..

facing below issue, please help

 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1022:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
     at onErrorNT (internal/child_process.js:366:16)
     at _combinedTickCallback (internal/process/next_tick.js:102:11)
     at process._tickCallback (internal/process/next_tick.js:161:9)
     at Function.Module.runMain (module.js:607:11)
     at startup (bootstrap_node.js:158:16)
     at bootstrap_node.js:575:3
 Error occured when executing command: npm run serve
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1022:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
     at onErrorNT (internal/child_process.js:366:16)
     at _combinedTickCallback (internal/process/next_tick.js:102:11)
     at process._tickCallback (internal/process/next_tick.js:161:9)
     at Function.Module.runMain (module.js:607:11)
     at startup (bootstrap_node.js:158:16)
     at bootstrap_node.js:575:3
[1] npm run serve exited with code -4058
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 start: `concurrently "npm run build:watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2017-07-23T09_04_20_447Z-debug.log

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
