### ISSUE TITLE
Please what is the cause of this error and what is the solution ?

### ISSUE THREAD

**Issue by clementcrownrise** [angular/quickstart#490]
$ npm install
module.js:471
    throw err;
    ^

Error: Cannot find module 'buffer-shims'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Double Edge\AppData\Roaming\npm\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:36:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
