### ISSUE TITLE
Cannot read property 'config' of null" while running "ng serve --open"

### ISSUE THREAD

**Issue by w3a-coder** [angular/quickstart#525]
Cannot read property 'config' of null" while running "ng serve --open"
Error :Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/home/w3a/angular/node_modules/@angular/cli/tasks/serve.js:51:63)
    at check_port_1.checkPort.then.port (/home/w3a/angular/node_modules/@angular/cli/commands/serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by gsrikanth007** [comment]
to resolve this issue need add .angular-cli.json file

**Comment by abyesarah** [comment]
where? and from where

**Comment by zijianhuang** [comment]
In the downloadable example mentioned in https://angular.io/guide/testing

**Comment by zimejin** [comment]
@gsrikanth007 thanks, that was it.

**Comment by rimbakasimba** [comment]
Have the config at proper place and same as my other projects, yet giving this error. Am on ver 5.2.2 of angular

**Comment by fengerzh** [comment]
In Angular 6, the file is renamed to `angular.json`, so you may need to run `npm install` to upgrade to Angular 6.

**Comment by josuevalrob** [comment]
Thanks for the angular 6 tip, @fengerzh 
But after run it I got this: 
Cannot read property 'config' of null

> TypeError: Cannot read property 'config' of null


```
    at Class.run (/Users/josue/WebDevelop/angudru/angdru/node_modules/@angular/cli/tasks/serve.js:51:63)
    at check_port_1.checkPort.then.port (/Users/josue/WebDevelop/angudru/angdru/node_modules/@angular/cli/commands/serve.js:123:26)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

**Comment by Mujeeb017** [comment]
Yes after npm install am too getting same error when use angular6.
But after run it I got this:
Cannot read property 'config' of null

TypeError: Cannot read property 'config' of null

    at Class.run (/Users/josue/WebDevelop/angudru/angdru/node_modules/@angular/cli/tasks/serve.js:51:63)
    at check_port_1.checkPort.then.port (/Users/josue/WebDevelop/angudru/angdru/node_modules/@angular/cli/commands/serve.js:123:26)
    at process._tickCallback (internal/process/next_tick.js:178:7)

**Comment by j-blandford** [comment]
the issue for us was that even though `@angular/cli` was meant to be v6+, it was actually downloading an old version 1.7.4

**Comment by vidhyakrish** [comment]
yes i had a similar issue - and @prasoc response helped me. my global ng cli (6.0.~)was different from local (1.5.0)and it was stopping my angular not updated to 6.0.0. (althogh the package.json had it).  Once i updated my local ng cli and reinstalled node modules i was able to run node scripts.

**Comment by gg-gg-v1** [comment]
Hi All,

I am using angular 4 app and I have same issue. I have` angular.json` file only but not .`angular-cli.json.` is there any way to still run the command `ng serve`  without explicitly placing` .angular-cli.json`  file in the directory ?

Actually my main goal is to convert the existing app to universal one.

Any help would be highly appreciated !!

Thanks

**Comment by amansehgalg** [comment]
You need to run the following command to solve this problem. First remove all the angular cli
npm uninstall -g angular-cli
npm uninstall -g @angular/cli
npm install -g @angular/cli
and then run check
ng serve --open

**Comment by mmamoonkhan** [comment]
Still have an error please tell me how to solve it i'm already waste 5 day's on it

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (C:\wamp64\www\Schoex32\upload\node_modules\@angular\cli\tasks\serve.js:21:63)
    at check_port_1.checkPort.then.port (C:\wamp64\www\Schoex32\upload\node_modules\@angular\cli\commands\serve.js:110:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! first@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the first@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mamoon\AppData\Roaming\npm-cache\_logs\2018-11-22T05_19_47_594Z-debug.log

**Comment by mitalippatel** [comment]
@mmamoonkhan check this one https://github.com/angular/angular-cli/issues/4736#issuecomment-341922263
that helped me to fix

**Comment by vitorpiovezam** [comment]
> to resolve this issue need add .angular-cli.json file

the @gsrikanth007 solution worked for me, in addition I will post here a default .angular-cli.json file

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "PROJECT_NAME"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```

**Comment by zeeshansafdar48** [comment]
> {
>   "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
>   "project": {
>     "name": "PROJECT_NAME"
>   },
>   "apps": [
>     {
>       "root": "src",
>       "outDir": "dist",
>       "assets": [
>         "assets",
>         "favicon.ico"
>       ],
>       "index": "index.html",
>       "main": "main.ts",
>       "polyfills": "polyfills.ts",
>       "test": "test.ts",
>       "tsconfig": "tsconfig.app.json",
>       "testTsconfig": "tsconfig.spec.json",
>       "prefix": "app",
>       "styles": [
>         "styles.css"
>       ],
>       "scripts": [],
>       "environmentSource": "environments/environment.ts",
>       "environments": {
>         "dev": "environments/environment.ts",
>         "prod": "environments/environment.prod.ts"
>       }
>     }
>   ],
>   "e2e": {
>     "protractor": {
>       "config": "./protractor.conf.js"
>     }
>   },
>   "lint": [
>     {
>       "project": "src/tsconfig.app.json"
>     },
>     {
>       "project": "src/tsconfig.spec.json"
>     },
>     {
>       "project": "e2e/tsconfig.e2e.json"
>     }
>   ],
>   "test": {
>     "karma": {
>       "config": "./karma.conf.js"
>     }
>   },
>   "defaults": {
>     "styleExt": "css",
>     "component": {}
>   }
> }

Thanks it works for me

**Comment by sunilbittu** [comment]
is it still required for angular 8 as well?

**Comment by prafful-panwar-ayur** [comment]
@amansehgalg Thanks :)

**Comment by jsersan** [comment]
Thank you very much!!!

**Comment by AnastasiusVivaldus** [comment]
I'm trying to run a legacy app with "@angular/cli": "^1.7.4" from a course created in 2017 and it's giving me the complaint `Cannot read property 'config' of null TypeError: Cannot read property 'config' of null`. It's crazy to try and upgrade any part of the system since that's likely to break things even more.  I'm very frustrated right now at angular's convoluted cli versioning. If it worked ~3 years ago then it ought to work now!

**Comment by sammysium** [comment]
> I'm trying to run a legacy app with "@angular/cli": "^1.7.4" from a course created in 2017 and it's giving me the complaint `Cannot read property 'config' of null TypeError: Cannot read property 'config' of null`. It's crazy to try and upgrade any part of the system since that's likely to break things even more. I'm very frustrated right now at angular's convoluted cli versioning. If it worked ~3 years ago then it ought to work now!

am in same boat as you! frustrating indeed
