### ISSUE TITLE
Cannot find module 'lodash' when running e2e tests

### ISSUE THREAD

**Issue by filipesilva** [angular/quickstart#65]
Trying to do `npm run e2e` gives the following error message:

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/dev/ideablade/quickstart (master)
$ npm run e2e

> angular2-quickstart@1.0.0 e2e E:\dev\ideablade\quickstart
> tsc && concurrently "http-server" "protractor protractor.config.js"

[1] ERROR - failed loading configuration file protractor.config.js
[1] E:\dev\ideablade\quickstart\node_modules\protractor\built\configParser.js:134
[1]             throw e;
[1]             ^
[1]
[1] Error: Cannot find module 'lodash'
[1]     at Function.Module._resolveFilename (module.js:337:15)
[1]     at Function.Module._load (module.js:287:25)
[1]     at Module.require (module.js:366:17)
[1]     at require (module.js:385:17)
[1]     at Object.<anonymous> (E:\dev\ideablade\quickstart\protractor.config.js:15:9)
[1]     at Module._compile (module.js:435:26)
[1]     at Object.Module._extensions..js (module.js:442:10)
[1]     at Module.load (module.js:356:32)
[1]     at Function.Module._load (module.js:311:12)
[1]     at Module.require (module.js:366:17)
[1] protractor protractor.config.js exited with code 1
[0] Starting up http-server, serving ./
[0] Available on:
[0]   http://192.168.0.12:8080
[0]   http://127.0.0.1:8080
[0] Hit CTRL-C to stop the server
```

This is because in `protractor.config.js` we do `var _ = require('lodash');`, but it is not present in the project dependencies.

I'll put up a PR for this.

**Comment by wardbell** [comment]
Fixed coincidentally with beta.16
